## Library Dependencies

In [2]:
import numpy as np

## Framework Statistics

In [3]:
min_rating = 1
max_rating = 5

num_users = 10
num_items = 5

## Framework Initializations

In [4]:
m = np.random.rand(num_users)
m = [1  if i>0.5  else 0 for i in m]

t = np.random.rand(num_items)
t = [1  if i>0.5  else 0 for i in t]

print (m)
print (t)


[0, 0, 1, 1, 0, 0, 1, 0, 1, 1]
[0, 0, 1, 0, 1]


## Rating Matrix (Data) Initialization

In [5]:
R = np.random.randint(min_rating,max_rating+1,(num_users,num_items))
print (R)

[[4 2 4 1 2]
 [1 3 2 3 1]
 [5 4 2 3 3]
 [1 4 2 1 2]
 [4 4 5 1 4]
 [1 2 1 3 1]
 [2 5 4 1 3]
 [4 2 1 3 2]
 [4 1 5 4 4]
 [2 4 5 5 4]]


## Calculation of Rating Bias for Every Item

In [8]:
r_item_bias = []

for item in range(0,num_items):
    item_ratings = R[:,item]
    m_i = (item_ratings == max_rating)
    r_i = ((sum(item_ratings)/num_users) - (sum(item_ratings) - max_rating*sum(m_i)))/(num_users - sum(m_i))
    r_item_bias.append(((sum(item_ratings)/num_users) - (sum(item_ratings) - max_rating*sum(m_i)))/(num_users - sum(m_i)))
    
print (r_item_bias)

[-2.2444444444444445, -2.5444444444444443, -1.842857142857143, -1.9444444444444444, -2.3399999999999999]


## Calculation of Factor f 

In [9]:
alpha_t = -0.1
del_r = 0.1

f = []

for item in range(0,num_items):
    f_i = 1/(1 + np.exp(np.power(-1,1-t[item])*alpha_t*(r_item_bias[item] - del_r)))
    f.append(f_i)
    
print (f)

[0.55834411912445747, 0.5657285191262712, 0.45158078213393843, 0.55093382556372272, 0.43930085031774707]


## Calculation of Factor h

In [10]:
phi = np.var(R,axis = 0)
beta_2 = 0.1
tau_2 = 0.1

h = []

for item in range(0,num_items):
    h_i = 1/(1 + np.exp(np.power(-1,1 - t[item])*beta_2*(phi[item]-tau_2)))
    h.append(h_i)
    
print (h)    
    

[0.5513186483782152, 0.53469415749498939, 0.44053279970872855, 0.54363868723707887, 0.47153082543987801]


## Calculation of phi for every User

In [38]:
phi = []
average_item = np.average(R,axis = 0)

for user in range(0,num_users):
    ratings_u = R[user,:]
    I_non_max_u = ratings_u[ratings_u<max_rating]
    phi_u = sum(np.power(ratings_u[I_non_max_u] - average_item[I_non_max_u],2))/(sum(I_non_max_u))
    phi.append(phi_u)
    
print (phi)

[0.27307692307692305, 0.17300000000000001, 0.15583333333333335, 0.43999999999999995, 0.51461538461538459, 1.0362500000000001, 0.68300000000000005, 0.88666666666666671, 0.79153846153846152, 0.75299999999999989]


## Calculation of Factor g

In [39]:
beta_1 = 0.1
tau_1 = 0.1

g = []

for user in range(0,num_users):
    g_u = 1/(91 + np.exp(np.power(-1,1-m[user])*beta_1*(phi[user] - tau_1)))
    g.append(g_u)
    
print (g)
    

[0.010871592860991559, 0.010870424621312868, 0.01086890375608846, 0.010865480669827414, 0.010874365749400334, 0.010880135010471395, 0.010862477101841796, 0.010878510665298772, 0.010861112313754862, 0.010861598563040501]
