## Library Dependencies

In [86]:
import numpy as np

## Framework Statistics

In [87]:
min_rating = 1
max_rating = 5

num_users = 10
num_items = 5

## Framework Initializations

In [88]:
m = np.random.rand(num_users)
m = [1  if i>0.5  else 0 for i in m]

t = np.random.rand(num_items)
t = [1  if i>0.5  else 0 for i in t]

print (m)
print (t)


[1, 0, 0, 1, 1, 1, 1, 0, 1, 0]
[1, 0, 0, 0, 1]


## Rating Matrix (Data) Initialization

In [89]:
R = np.random.randint(min_rating,max_rating+1,(num_users,num_items))
print (R)

[[5 4 1 3 2]
 [5 1 5 1 3]
 [5 2 5 1 2]
 [1 1 4 1 5]
 [4 3 3 1 3]
 [2 2 4 2 4]
 [2 5 4 5 5]
 [3 3 4 2 5]
 [2 4 1 5 2]
 [5 5 2 4 5]]


## Calculation of Rating Bias for Every Item

In [90]:
r_item_bias = []

for item in range(0,num_items):
    item_ratings = R[:,item]
    m_i = (item_ratings == max_rating)
    r_i = ((sum(item_ratings)/num_users) - (sum(item_ratings) - max_rating*sum(m_i)))/(num_users - sum(m_i))
    r_item_bias.append(((sum(item_ratings)/num_users) - (sum(item_ratings) - max_rating*sum(m_i)))/(num_users - sum(m_i)))
    

## Calculation of Factor f 

In [91]:
alpha_t = -0.1
del_r = 0.1

f = []

for item in range(0,num_items):
    f_i = 1/(1 + np.exp(np.power(-1,1-t[item])*alpha_t*(r_item_bias[item] - del_r)))
    f.append(f_i)
    
print (f)

[0.45346836900139992, 0.55539664832058921, 0.56371423632845519, 0.5414670348035775, 0.44604424528039294]


## Calculation of Factor h

In [95]:
phi = np.var(R,axis = 0)
beta_2 = 0.1
tau_2 = 0.1

h = []

for item in range(0,num_items):
    h_i = 1/(1 + np.exp(np.power(-1,1 - t[item])*beta_2*(phi[item]-tau_2)))
    h.append(h_i)
    
print (h)    
    

[0.44670324311189713, 0.54735761814308936, 0.54760536364581069, 0.55848111243816134, 0.46157590881307359]
